name: Automated CR with codellama
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ollama
        uses: ai-action/setup-ollama@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Code review comment
        run: |
          PROMPT='You are a senior software engineer reviewing a Git diff. Analyze the following code changes carefully and provide a professional code review. Focus on:
            Code quality and structure
            Adherence to best practices and conventions (language/framework-specific)
            Readability and maintainability
            Potential bugs or logical issues
            Opportunities for simplification or refactoring
            Security issues (if relevant)
          Only comment on lines that are added or changed. If the code looks good, briefly acknowledge that. Be concise and constructive in your feedback. The changes are below:'
          RESPONSE=$(ollama run codellama "$PROMPT\n$(gh pr diff $PR_NUMBER)")
          gh pr comment $PR_NUMBER --body "$RESPONSE"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}